# Generated by Django 4.2.1 on 2024-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
