# Generated by Django 4.2.1 on 2024-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0007_student_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=10)),
                ('room_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='mess',
        ),
    ]
