# Generated by Django 4.2.1 on 2024-06-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0008_sroom_delete_mess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_no',
        ),
    ]
